---
title: "Data Viz-Class"
author: "Desik Somasundaram"
date: "8/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# General use packages:
library(tidyverse)
library(here)
library(janitor)

# Specifically for plots:
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)

# And for another dataset we'll explore:
library(gapminder)

# Spatial
library(sf)

```

```{r}
lizards <- read_csv(here("data_tidy","lizards.csv"))

```
Histogram (really bad) of lizard weights

Colors- points and lines
Fill- fill

```{r}
ggplot(data = lizards, aes(x = weight)) + 
  geom_histogram(color = "orange", fill = "purple")
```
```{r}
# total length on x-axis
# weight on y-axis

ggplot(data = lizards, aes(x = total_length, y = weight)) + geom_point(shape = 172, fill = "green", color = "blue", size = 4, alpha = 0.5)
```

 
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) + 
  geom_point(aes(color = common_name)) + 
  theme_light() +
  facet_wrap(~site, ncol = 3)
```
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) + 
  geom_point(aes(color = common_name)) + 
  theme_light() +
  facet_grid(sex ~ tail)
```

```{r}
lizard_counts <- lizards %>% 
  group_by(common_name) %>% 
  summarize(count = n())


```

```{r}
ggplot(data = lizard_counts, aes(y = fct_reorder(common_name, count), x = count)) +
  geom_col(aes(fill = common_name)) +
  labs( x = "Lizard counts", y = "Common Names")

```
```{r}
lizards_reorder <- lizard_counts %>% 
  mutate(common_name = fct_reorder(common_name, count))
```

## Axis scale break, limit & labels

Scatterplot: total_length (x) versus weight (y)


```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) + 
  geom_point() +
  scale_x_continuous(breaks = c(50, 100, 200, 500),
                     limits = c(0,500)) 
```
```{r}
lizard_counts <- lizards %>%
  mutate(date = lubridate::mdy(date)) %>%
  group_by(date) %>% 
  summarize(count = n())

class(lizard_counts$date)

```
```{r}
ggplot(data = lizard_counts, aes(x = date, y = count)) +
  geom_line() +
  scale_x_date(breaks = scales::breaks_width("3 years"), labels = scales::label_date("%y"))
```
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point((aes(color = weight))) +
  scale_color_gradientn(colors = c("red", "navy", "cyan", "chartreuse", "orange"))

```
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = weight)) +
  scale_color_steps2(colors = c("green", "blue", "purple"),
                     breaks = c(0, 20, 40, 50, 100))
```
```{r}
lizard_fct <- lizards %>% 
  mutate(common_name = fct_reorder(common_name, total_length, .fun = median))


ggplot(data = lizard_fct, aes(x = total_length, y = common_name)) + 
  geom_boxplot(aes(fill = common_name), show.legend = FALSE) +
  scale_fill_paletteer_d("nbapalettes::nuggets_80s")
```
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  theme(
    panel.background = element_rect(fill = "yellow", 
                                    color = "purple",
                                    size = 10),
    panel.grid.major.x = element_line(color = "blue"),
    panel.grid.major.y = element_line(color = "green"),
    plot.background = element_rect(fill = "cyan")
  )
```

